### ISSUE TITLE
Three Black Crows Task List

### ISSUE THREAD

**Issue by bahooki** [Allan1212/PMHF-Inc#3]
- [ ] Capabilities to pass a list of tickers, rather than one ticker at a time
- [ ] Capability to pass different time frames; currently only works day by day. Ideally should be able to look hour by hour, month by month, etc. 
- [ ] Tune model (or research) to find the best value for what dictates a "full" candle

**Comment by mario-cristiani** [comment]
Closing this issue and re-creating from a card so that we can see it on the project tasks page.
